name: Build Custom Kernel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up build environment
      run: sudo apt-get update && sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev

    - name: Build kernel
      run: |
        chmod +x scripts/build.sh
        ./scripts/build.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: kernel-packages
        path: output/
